# Generated by Django 3.0.2 on 2020-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200120_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
